config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "restaurants#index"

  resources :restaurants do
    resources :reviews, only: [:new, :create, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  CATEGORIES = [
    "fast_food",
    "casual_dining",
    "contemporary",
    "cafes",
    "pizzerias",
    "pop_up",
    "ghost"
  ]

  validates :name, :description, :category, :address, :zipcode, :city, :phone_number, presence: true
  validates :name, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user

  enum grade: { awful: 0, fine: 1, incredible: 2 }

  validates :content, :grade, :user_id, :restaurant_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :restaurants
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_restaurant, only: [:show, :edit, :update]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user

    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurants_path
    else
      render :edit
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.includes(:user, :reviews).find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :category, :photo, :address, :zipcode, :city, :phone_number, :opens_at, :closes_at)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update]
  before_action :set_restaurant, only: [:new, :create, :edit]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to restaurant_path(@review.restaurant)
    else
      render :edit
    end
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:grade, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
    def meta_title
      content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
    end
  
    def meta_description
      content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
    end
  
    def meta_image
      meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
      # little twist to make it work equally with an asset or a url
      meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
    end
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag "favicon.png", rel: "icon", type: "image/png" %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>">
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:image" content="<%= meta_image %>">
    <meta property="og:description" content="<%= meta_description %>">
    <meta property="og:site_name" content="<%= meta_title %>">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    
    <%= render 'shared/pwa_links' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for restaurant do |f| %>
  <%= f.input :name,
              wrapper_html: { class: "mb-4" },
              label_html: { class: "form-label text-secondary fw-bold" } %>
  <%= f.input :description,
              wrapper_html: { class: "mb-4" },
              label_html: { class: "form-label text-secondary fw-bold" } %>
  <%= f.input :photo,
              as: :file,
              wrapper_html: { class: "mb-4" },
              label_html: { class: "form-label text-secondary fw-bold" } %>
  <div class="row">
    <div class="col">
      <%= f.input :phone_number,
                  wrapper_html: { class: "mb-4" },
                  label_html: { class: "form-label text-secondary fw-bold" } %>
    </div>
    <div class="col">
      <%= f.input :category,
                  as: :select,
                  collection: Restaurant::CATEGORIES,
                  wrapper_html: { class: "mb-4" },
                  label_html: { class: "form-label text-secondary fw-bold" } %>
    </div>
  </div>
  <%= f.input :address,
              wrapper_html: { class: "mb-4" },
              label_html: { class: "form-label text-secondary fw-bold" } %>
  <div class="row">
    <div class="col">
      <%= f.input :zipcode,
                  wrapper_html: { class: "mb-4" },
                  label_html: { class: "form-label text-secondary fw-bold" } %>
    </div>
    <div class="col">
      <%= f.input :city,
                  wrapper_html: { class: "mb-4" },
                  label_html: { class: "form-label text-secondary fw-bold" } %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= f.input :opens_at, as: :string,
                  wrapper_html: { class: "mb-4" },
                  label_html: { class: "form-label text-secondary fw-bold" },
                  input_html: { data: { controller: "flatpickr" } } %>
    </div>
    <div class="col">
      <%= f.input :closes_at, as: :string,
                  wrapper_html: { class: "mb-4" },
                  label_html: { class: "form-label text-secondary fw-bold" },
                  input_html: { data: { controller: "flatpickr" } } %>
    </div>
  </div>
  <%= f.submit restaurant.new_record? ? "Create restaurant" : "Update restaurant", class:"btn btn-primary" %>
<% end %>

app/views/restaurants/_restaurant_card.html.erb
<div class="card mb-4" data-controller="popover" data-bs-toggle="popover" data-bs-placement="right" data-bs-trigger="hover" data-bs-content="<%= restaurant.description %>">
  <div class="card-body">
    <h5 class="card-title"><%= restaurant.name %></h5>
    <i class="fa-solid fa-circle-info" data-controller="tooltip"  data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="<%= pluralize(restaurant.reviews.size, "review") %>"></i>
    <p class="card-text"><%= restaurant.description.truncate(86) %></p>
    <%= link_to "See restaurant", restaurant_path(restaurant), class: "btn btn-success" %>
    <%= link_to "Edit", edit_restaurant_path(restaurant), class: "ms-3 link-secondary" %>
  </div>
</div>

app/views/restaurants/edit.html.erb
<div class="container">
  <div class="row">
    <div class="pt-5 col-md-8 offset-md-2">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to "Back to list", restaurants_path %></li>
          <li class="breadcrumb-item active" aria-current="page">Edit restaurant</li>
        </ol>
      </nav>
      <h1 class="pb-3">Edit restaurant</h1>
      <%= render "form", restaurant: @restaurant %>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h1>Restaurants</h1>
      <%= link_to "Create a new restaurant", new_restaurant_path , class:"btn btn-ferrari" %>
    </div>
  </div>

  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-md-4">
        <%= render "restaurant_card", restaurant: restaurant %>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="pt-5 col-md-8 offset-md-2">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to "Back to list", restaurants_path %></li>
          <li class="breadcrumb-item active" aria-current="page">New restaurant</li>
        </ol>
      </nav>
      <h1 class="pb-3">New restaurant</h1>
      <%= render "form", restaurant: @restaurant %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<% content_for :meta_title, "#{@restaurant.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @restaurant.description %>
<% content_for :meta_image, cl_image_path(@restaurant.photo.key) if @restaurant.photo.attached? %>

<div class="container">
  <div class="row pt-5">
    <div class="col-md-8 offset-md-2">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to "Back to list", restaurants_path %></li>
        </ol>
      </nav>

      <div class="d-flex mb-4">
        <%= cl_image_tag(@restaurant.photo.key, class: "img-thumbnail", width: 100, height: 100, crop: :fill) if @restaurant.photo.attached? %>
        <div class="<%= @restaurant.photo.attached? ? 'ms-3' : '' %>">
          <h1 class="mb-0"><%= @restaurant.name %></h1>
          <span class="badge rounded-pill bg-success mb-3"><%= @restaurant.category %></span>
        </div>
      </div>

      <p><%= @restaurant.description %></p>

      <div class="d-flex">
        <i class="fa-solid fa-location-pin me-2"></i>
        <address>
          <%= @restaurant.address %><br>
          <%= @restaurant.zipcode %> <%= @restaurant.city %>
        </address>
      </div>

      <div class="dropdown">
        <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          Book a table
        </a>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li><%= phone_to @restaurant.phone_number, "Call us", class: "dropdown-item" %></li>
          <li><%= mail_to @restaurant.user.email, "Send us an email", class: "dropdown-item" %></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="row pt-5">
    <div class="col-md-8 offset-md-2">
      <div class="d-flex align-items-center mb-3">
        <h2>Reviews</h2>
        <%= link_to "Add a review", new_restaurant_review_path(@restaurant), class: "ms-3 mb-0" %>
      </div>

      <div class="row">
        <% @restaurant.reviews.each do |review| %>
          <div class="mb-3 col-md-4">
            <%= render "reviews/review_card", review: review %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<div data-controller="character-counter">
<%= simple_form_for [restaurant, review] do |f| %>
  <%= f.input :content,
              wrapper_html: { class: "mb-4" },
              input_html: { data: { character_counter_target: "input" } },
              label_html: { class: "form-label text-secondary fw-bold" } %>
  <%= f.input :grade,
              as: :select,
              collection: Review.grades.keys,
              wrapper_html: { class: "mb-4" },
              label_html: { class: "form-label text-secondary fw-bold" } %>
  
  <p>Description is currently <strong data-character-counter-target="counter"></strong> characters long.</p>

  <%= f.submit review.new_record? ? "Add review" : "Update review", class:"btn btn-primary" %>
<% end %>
</div>

app/views/reviews/_review_card.html.erb
<div class="card text-dark bg-light">
  <div class="card-header"><small>Posted by: <%= review.user.email %></small></div>
  <div class="card-body">
    <span class="badge bg-info text-dark mb-2"><%= review.grade %></span>
    <p class="card-text"><%= review.content %></p>
    <%= link_to "Edit", edit_restaurant_review_path(review.restaurant, review), class: "link-secondary" %>
  </div>
</div>

app/views/reviews/edit.html.erb
<div class="container">
  <div class="row">
    <div class="pt-5 col-md-8 offset-md-2">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to "Back to restaurant", restaurant_path(@restaurant) %></li>
          <li class="breadcrumb-item active" aria-current="page">Edit review</li>
        </ol>
      </nav>
      <h1 class="pb-3">Edit your review of <%= @restaurant.name %></h1>
      <%= render "form", restaurant: @restaurant, review: @review %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="pt-5 col-md-8 offset-md-2">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to "Back to restaurant", restaurant_path(@restaurant) %></li>
          <li class="breadcrumb-item active" aria-current="page">New review</li>
        </ol>
      </nav>
      <h1 class="pb-3">Add your review of <%= @restaurant.name %></h1>
      <%= render "form", restaurant: @restaurant, review: @review %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Create a new restaurant", new_restaurant_path , class:"dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">